config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root to: 'projects#index'

  namespace :users do
    resources :profiles, only: :show
  end

  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations => "users/registrations"
  }

  devise_scope :user do
    get '/users/sign_up_with_token/:token', to: 'users/registrations#new_with_invite_token', as: :new_user_registration_with_token
  end

  resources :projects, only: [:index, :show, :new, :create] do
    resources :lists, only: :create
  end
  get 'lists/:list_id/tasks/new', to: 'tasks#new', as: 'new_task'
  post 'lists/:list_id/tasks', to: 'tasks#create', as: 'list_tasks'
  resources :tasks, only: :show

  resources :invites, only: [:create]

  get 'pages/*page' => 'pages#show'
  post 'quiz' => 'pages#create'

  resources :activities

  namespace :api do
    #mount_devise_token_auth_for 'User', at: 'auth'
    namespace :v1 do
      jsonapi_resources :projects
      jsonapi_resources :lists
      jsonapi_resources :tasks do
        jsonapi_related_resources :members
        jsonapi_related_resources :todos
      end
      jsonapi_resources :todos do
        jsonapi_related_resource :task
      end
      jsonapi_resources :users do
        jsonapi_related_resources :tasks
      end
      jsonapi_resource :assignments, only: [:create, :destroy] do
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include Invitable

  validates_presence_of :title

  belongs_to :owner, class_name: 'User'

  has_many :memberships, as: :resource, dependent: :destroy
  has_many :members, through: :memberships, :source => :user

  has_many :invites, as: :invitable, dependent: :destroy

  has_many :lists
end

app/controllers/api/v1/projects_controller.rb
module Api::V1
  class ProjectsController < ApiController
#    def index
#       render json: current_api_user.projects, include: 'members'
#    end
#
#    def create
#      @project = current_api_user.projects.create(project_params)
#
#      if @project.persisted?
#        render json: @project, status: :created
#      else
#        render_error resource: @project, status: 422
#      end
#    end
#
#    def show
#      project = Project.find_by(id: params[:id])
#
#      if project
#        if current_api_user.has_any_role_scoped_to?(resource: project)
#          render json: project, status: 200
#        else
#          render json: { errors: [{detail: 'Sorry, you are not authoirized to access this resource'}] }, status: 401
#        end
#      else
#        render json: { errors: [{detail: 'This project does not exist'}] }, status: 404
#      end
#    end
#
#    private
#
#    def project_params
#      ActiveModelSerializers::Deserialization
#        .jsonapi_parse(params, only: [:title, :description])
#    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.projects
  end

  def new
    @project = Project.new
  end

  def show
    project = Project.find_by(id: params[:id])

    unless project.present?
      redirect_to root_url, notice: "This project does not exist" and return
    end

    unless project.members.include? current_user
      redirect_to root_url, notice: "You are not authorized to access this page" and return
    end

    render locals: { 
      project: project
    }
  end

  def create
    @project = current_user.projects.create(project_params)

    if @project.persisted?
      flash[:success] = "New project created successfully"
      redirect_to project_path @project
    else
      render :new
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/views/projects/_member.html.haml
.item
  %img.ui.avatar.image{:src => "#{member.gravatar_url}"}

app/views/projects/index.html.haml
%section.row
  .column
    .ui.four.cards
      =link_to new_project_path, class: "card" do
        .content
          .center.aligned
            %i.plus.circle.icon
            Create New Project

      - @projects.each do |project|
        =link_to project_path(project), class: "card" do
          .content
            .header= project.title
            .description= project.description

app/views/projects/new.html.haml
.sixteen.wide.column
  .ui.three.column.centered.grid
    .column
      .ui.segment
        .ui.header
          Create New Project
        = simple_form_for @project, class: 'ui form' do |f|
          .field
            = f.input :title, label: 'Title'
            = f.input :description, label: 'Description'

          = f.submit 'Save', class: "ui primary button"

app/views/projects/show.html.haml
:javascript
  $(function() {
    /* Invite form */
    $('#btn-invite').on('click', function() {
      $('.modal#invite-form').modal('show');
    });
  });

- content_for :invite_form_validation do
  = javascript_include_tag 'invite-form-validation'

= javascript_pack_tag 'task_lists'

.hidden#activities{'data-project-id' => project.id}

.sixteen.wide.column 
  .ui.horizontal.divided.list
    .item
      %h3= project.title
    .item
      .ui.horizontal.list
        = render partial: 'projects/member', collection: project.members
        .item
          .tiny.ui.button#btn-invite Invite

= react_component('TaskLists', {project_id: project.id, current_user_id: current_user.id}, {class: 'row'})

-# Modal for invite form
= render "#{(invite ||= project.invites.new).to_partial_path}_form", invite: invite